spring:
    #数据库配置
    datasource:
       url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
       username: root
       password: 123456
       driver-class-name: com.mysql.jdbc.Driver
       
    #redis配置  
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      timeout: 60000 
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 500
        
    #activemq配置
    activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
      in-memory: true
      pool:
        enabled: false

server:
  #tomcat配置        
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
  port: 8080
  
 